### ISSUE TITLE
0.0.10 listPaymentMethods missing `items`

### ISSUE THREAD

**Issue by nhibberd** [gettilled/tilled-node#13] opened 2023-10-31 18:47 UTC
I could be missing something here, I am trying to upgrade from 0.0.9 to 0.0.10 and seeing a number of failures. One is around the listPaymentMethods api. `items` is now missing from the response types, namely it no longer includes the `ListPaymentMethods200ResponseAllOf` interface.

The code from [list-payment-methods200-response](https://github.com/gettilled/tilled-node/blob/main/model/list-payment-methods200-response.ts) and the version in npm:
<img width="801" alt="image" src="https://github.com/gettilled/tilled-node/assets/447873/425ef850-8152-4146-b75a-a9150df04cc6">

**Comment by dpatton1992** [comment] 2023-11-01 17:41
Hey @nhibberd, thanks for bringing this to our attention. I'm not sure why automation did not catch this, but I have recreated the error and will have a patch out asap.

**Comment by dpatton1992** [comment] 2023-11-01 20:33
the issue is we didn’t have the openapitools.json file committed to the repository. This file sets the openapi generator cli to a specific version 6.5. There are some issues with the latest version 7.1 and our codebase which was used to build tilled-node 0.0.10. We have committed this file to the repo and pushed the code and a new package 0.0.11 and the issue seems to be resolved.

We are looking to add some automated testing around this process.

**Closed by dpatton1992** 2023-11-01 20:33 UTC
